import os

SENTRY_DSN = os.getenv('SENTRY_DSN')
CLOSEIO_API_KEY = os.getenv("CLOSEIO_API_KEY")

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')